from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
import os
from openai import OpenAI
from pinecone import Pinecone, ServerlessSpec
from dotenv import load_dotenv
import os
import time

load_dotenv()

# llm = ChatOpenAI(
#     model="gpt-4o-mini"
# )

# response = llm.invoke(
#     "Hello! Good Morning."
# )

# response1 = llm.invoke("Who is sachin")

# print(response.content)




# OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# client = OpenAI(api_key=OPENAI_API_KEY)

# prompt = f"""
#         You are a helpful AI assistant.

#        give me details about sachin
#         """

# response = client.chat.completions.create(
#         model="gpt-4o-mini",
#         messages=[
#             {
#                 "role": "system",
#                 "content": "You are a helpful AI assistant"
#             },
#             {
#                 "role": "user",
#                 "content": prompt
#             }
#         ]
#     )

# prompt2 = f"""
#         You are a helpful AI assistant.

#        give me details about sachin
#         """

# response = client.chat.completions.create(
#         model="gpt-4o-mini",
#         messages=[
#             {
#                 "role": "system",
#                 "content": "You are a helpful AI assistant"
#             },
#             {
#                 "role": "user",
#                 "content": prompt2
#             }
#         ]
#     )

# print(response)


# from langchain_core.prompts import PromptTemplate

# prompt = PromptTemplate.from_template(
#     "Explain {topic} for beginners in {count} points"
# )

# formatted_prompt_ml = prompt.format(
#     topic="Machine Learning",
#     count=3
# )


# formatted_prompt_dl = prompt.format(
#     topic="Deep learning",
#     count=30
# )

# print(formatted_prompt_ml)
# print(formatted_prompt_dl)



# from langchain_openai import ChatOpenAI
# from langchain_core.output_parsers import StrOutputParser
# from dotenv import load_dotenv

# load_dotenv()

# llm = ChatOpenAI(model="gpt-4o-mini")

# parser = StrOutputParser()

# response = llm.invoke(
#     "List 3 cloud platforms"
# )

# print(response)

# final_output = parser.invoke(response)

# print(final_output)



# llm , prompt, parser


# chain (prompt => llm => parser)



# from langchain_openai import ChatOpenAI
# from langchain_core.prompts import PromptTemplate
# from langchain_core.output_parsers import StrOutputParser
# from dotenv import load_dotenv

# load_dotenv()

# title_prompt = PromptTemplate.from_template(
#     "Give me a trending catchy title for {topic}"
# )

# llm = ChatOpenAI(model="gpt-4o-mini")

# parser = StrOutputParser()

# print("Prompt : " )
# print(title_prompt)
# print("llm : " )
# print(llm)
# print("Parser")
# print(parser)

# title_gen = title_prompt | llm | parser


# title = title_gen.invoke({
#     "topic": "Artificial Intelligence"
# })

# print("Title : " + title)




from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from dotenv import load_dotenv

load_dotenv()


title_prompt = PromptTemplate.from_template(
    "Give me a trending catchy title for {topic}"
)

content_prompt = PromptTemplate.from_template(
    "Give me content for the title : {title}"
)

llm = ChatOpenAI(model="gpt-4o-mini")

parser = StrOutputParser()


# chain 1 (generate the title from topic)
title_gen = title_prompt | llm | parser

# chain 2 (generate the content from the title - generated by chain 1)
content_gen = content_prompt | llm | parser

title = title_gen.invoke({
    "topic": "GenAI Night Class"
})

print("Title : " + title)

content = content_gen.invoke({
    "title" : title
})


print("Content : " + content)

#  topic    llm    title          llm   content 
# input => llm => init output => llm => final output 



# topic   => llm      =>  title   =>  llm     =>  content
# input   =>  llm     =>  output  =>  llm     =>  final_output 



# from dotenv import load_dotenv

# from langchain_openai import ChatOpenAI
# from langchain.memory import ConversationBufferMemory
# from langchain.chains import ConversationChain

# load_dotenv()

# llm = ChatOpenAI(
#     model="gpt-4o-mini"
# )

# memory = ConversationBufferMemory(
#     return_messages=True
# )

# conversation = ConversationChain(
#     llm=llm,
#     memory=memory,
#     verbose=True
# )

# response1 = conversation.predict(
#     input="My name is Alex"
# )

# print(response1)

# response2 = conversation.predict(
#     input="What is my name?"
# )

# print(response2)